- type: latheRecipe
  id: Binoculars
  result: Binoculars
  completetime: 2
  materials:
    Steel: 200
    Glass: 200

- type: latheRecipe
  id: WeaponEnergyAutorifle
  result: WeaponEnergyAutorifle
  completetime: 6
  materials:
    Steel: 1800
    Glass: 400
    Plastic: 250