- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Bagel
  - Box
  - Convex
  #- Core
  - Elkridge
  - Fland
  #- Gate
  - Marathon
  - Oasis
  - Omega
  - Packed
  - Plasma
  - Reach
  # LateStation
  - Sierra
