name: Publish

concurrency:
  group: publish

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.6.0
      with:
        submodules: 'recursive'

    - name: Install Python dependencies
      run: pip3 install requests pyyaml

    - name: Update Changelog YAML
      run: python3 Tools/update_changelog.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit Changelog Changes
      run: |
        git config --global user.name "Weh Bot"
        git config --global user.email "weh-bot@noreply.github.com"
        
        # Set the remote URL with PAT for authentication
        git remote set-url origin https://x-access-token:${{ secrets.WEH_BOT_PAT }}@github.com/LateStation14/Late-station-14.git
        
        # Fetch and pull the latest changes from master
        git fetch origin
        git pull origin master --rebase
        
        # Add and commit the updated changelog
        git add Resources/Changelog/LateStation.yml
        git commit -m "Auto-update changelog [skip ci]" || echo "No changes to commit"
        
        # Push to master
        git push origin master
      env:
        WEH_BOT_PAT: ${{ secrets.WEH_BOT_PAT }}

    - name: Install dependencies
      run: sudo apt-get install -y python3-paramiko python3-lxml

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 9.0.x

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform win-x64 --platform linux-x64 --platform osx-x64 --platform linux-arm64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    - name: Upload build artifact
      id: artifact-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: release/*.zip
        compression-level: 0
        retention-days: 0

    - name: Publish version
      run: Tools/publish_github_artifact.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        ARTIFACT_ID: ${{ steps.artifact-upload-step.outputs.artifact-id }}
        GITHUB_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}

    - name: Publish changelog (Discord)
      run: Tools/actions_changelogs_since_last_run.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISCORD_WEBHOOK_URL: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK }}

#    - name: Publish changelog (RSS)
#      run: Tools/actions_changelog_rss.py
#      env:
#        CHANGELOG_RSS_KEY: ${{ secrets.CHANGELOG_RSS_KEY }}

    - uses: geekyeggo/delete-artifact@v5
      if: always()
      with:
        name: build
